style = "grid" # display style, one of: "grid", "tree", or "oneline"
long = false # enable long listing mode
interactive = false # enable interactive mode

[eza]
# args forwarded to eza
args = [
  "-a",
  "--git-ignore",
  "--icons=always",
  "--color-scale=all",
  "--color-scale-mode=gradient",
  "--header",
  "--binary",
  "--group",
  "--git",
  "--level=5",
]

# args forwarded to eza only in interactive mode
interactive_args = ["--color=always"]

[pager]
# the name of the pager binary to use
bin = "less"
# args forwarded to the pager
args = ["-R"]
