style = "auto" # display style, one of: "auto", "grid", "tree", or "oneline"
long = false # enable long listing mode
ignore = true # respect .gitignore

[eza]
# args forwarded to eza
args = [
  "-a",
  "--icons=always",
  "--color-scale=all",
  "--color-scale-mode=gradient",
  "--header",
  "--binary",
  "--group",
  "--git",
  "--level=5",
]

# args forwarded to eza only when paged
interactive_args = ["--color=always"]

[pager]
# when output will be paged
when = "auto"

# the name of the pager binary to use
bin = "less"

# args forwarded to the pager
args = ["-R"]
